app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::bind('product', function($slug){
	return App\Product::where('slug', $slug)->first();
});
// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});
// Subproduct dependency injection
Route::bind('subproduct', function($subproduct){
    return App\Subproduct::find($subproduct);
});
// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});
Route::bind('user2', function($user){
    return App\User::find($user);
});
Route::bind('user3', function($user){
    return App\User::find($user);
});

Route::get('/', [
	'as' => 'home',
	'uses' => 'StoreController@index'
]);
Route::get('product/{slug}', [
	'as' => 'product-detail',
	'uses' => 'StoreController@show'
]);
// Carrito -------------
Route::get('cart/show', [
	'as' => 'cart-show',
	'uses' => 'CartController@show'
]);

Route::post('cart/add/{product}', [
	'as' => 'cart-add',
	'uses' => 'CartController@add'
]);


Route::get('cart/delete/{product}',[
	'as' => 'cart-delete',
	'uses' => 'CartController@delete'
]);
Route::get('cart/trash', [
	'as' => 'cart-trash',
	'uses' => 'CartController@trash'
]);
Route::get('cart/update/{product}/{quantity}', [
	'as' => 'cart-update',
	'uses' => 'CartController@update'
]);
Route::get('order-detail', [
	'middleware' => 'auth:user',
	'as' => 'order-detail',
	'uses' => 'CartController@orderDetail'
]);
// Authentication routes...
Route::get('auth/login', [
	'as' => 'login-get',
	'uses' => 'Auth\AuthController@getLogin'
]);
Route::post('auth/login', [
	'as' => 'login-post',
	'uses' => 'Auth\AuthController@postLogin'
]);
Route::get('auth/logout', [
	'as' => 'logout',
	'uses' => 'Auth\AuthController@getLogout'
]);
// Registration routes...
Route::get('auth/register', [
	'as' => 'register-get',
	'uses' => 'Auth\AuthController@getRegister'
]);
Route::post('auth/register', [
	'as' => 'register-post',
	'uses' => 'Auth\AuthController@postRegister'
]);

//recover

Route::get('auth/recover', [
	'as' => 'recover-get',
	'uses' => 'Auth\RecoverController@index'
]);

Route::post('auth/recover', [
	'as' => 'recover-post',
	'uses' => 'Auth\RecoverController@recover'
]);

Route::get('auth/modify/{token}', [
	'as' => 'modify-get',
	'uses' => 'Auth\ModifyController@index'
]);

Route::post('auth/modify', [
	'as' => 'modify-post',
	'uses' => 'Auth\ModifyController@modify'
]);

//Flow
Route::post('flow/confirmacion', [

	'as' => 'flow-confirmacion',
	'uses' => 'FlowController@confirmacion'
]);

Route::post('flow/fracaso', [

	'as' => 'flow-fracaso',
	'uses' => 'FlowController@fracaso'
]);

Route::post('flow/exito', [
	
	'as' => 'flow-exito',
	'uses' => 'FlowController@exito'
]);

//Khipu
Route::post('khipu/confirmacion', [

	'as' => 'khipu-confirmacion',
	'uses' => 'KhipuController@confirmacion'
]);

Route::get('khipu/fracaso', [

	'as' => 'khipu-fracaso',
	'uses' => 'KhipuController@fracaso'
]);

Route::get('khipu/exito', [

	'as' => 'khipu-exito',
	'uses' => 'KhipuController@exito'
]);

// ADMIN -------------
Route::group(['namespace' => 'Admin', 'middleware' => ['auth'], 'prefix' => 'admin'], function()
{

	Route::get('home', function(){
		return view('admin.home');
	});

	Route::resource('category', 'CategoryController');
	Route::resource('product', 'ProductController');
	Route::resource('subproduct', 'SubproductController');
	Route::resource('user', 'UserController');
	Route::resource('stock', 'StockController');
	Route::resource('reporteventas', 'ReporteVentasController');
	
	
	Route::get('orders', [
		'as' => 'admin.order.index',
		'uses' => 'OrderController@index'
	]);
	Route::post('order/get-items', [
	    'as' => 'admin.order.getItems',
	    'uses' => 'OrderController@getItems'
	]);

	
	Route::get('order/{id}', [
	    'as' => 'admin.order.destroy',
	    'uses' => 'OrderController@destroy'
	]);
	
	
		Route::post('stock', [
	    'as' => 'admin.stock.index',
	    'uses' => 'StockController@index'
	]);
	
	
	
//	Route::get('/getexport','StockController@getexport');
	
	Route::get('getexport/{cbcstock}', [
	    'as' => 'admin.stock.getexport',
	    'uses' => 'StockController@getexport'
	]);	
	
	
	
		Route::post('getexportventa/{desde}', [
	    'as' => 'admin.reporteventas.getexport',
	    'uses' => 'ReporteVentasController@getexport'
	]);	
	
	
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::resource('user2', 'UserController@edit2');

});
	
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::resource('user3', 'UserController@update');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::get('mispedidos', [
	    'as' => 'admin.user4.mispedidos',
	    'uses' => 'UserController@mispedidos'
	]);	

});

resources/views/admin/home.blade.php
@extends('admin.template')

@section('content')

    <div class="container text-center">
        <div class="page-header">
            <h1><i class="fa fa-rocket"></i> MI TIENDA - PANEL DE ADMINISTRACIÓN</h1>
        </div>
        
        <h2>Bienvenido(a) {{ Auth::user()->user }} al Panel de administración de tu tienda en línea.</h2><hr>
        
        <div class="row">
            
            <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-list-alt icon-home"></i>
                    <a href="{{ route('admin.category.index') }}" class="btn btn-warning btn-block btn-home-admin">CATEGORÍAS</a>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-shopping-cart  icon-home"></i>
                    <a href="{{ route('admin.product.index') }}" class="btn btn-warning btn-block btn-home-admin">PRODUCTOS</a>
                </div>
            </div>
              
        </div>
        
        <div class="row">
                           <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-list-ol icon-home"></i>
                    <a href="{{ route('admin.subproduct.index') }}" class="btn btn-warning btn-block btn-home-admin">SUB-PRODUCTOS</a>
                </div>
            </div>   
            <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-cc-paypal  icon-home"></i>
                    <a href="{{ route('admin.order.index') }}" class="btn btn-warning btn-block btn-home-admin">PEDIDOS</a>
                </div>
            </div> 
            
            <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-users  icon-home"></i>
                    <a href="{{ route('admin.user.index') }}" class="btn btn-warning btn-block btn-home-admin">USUARIOS</a>
                </div>
            </div>
			
             <div class="col-md-6">
                <div class="panel">
                    <i class="fa fa-book  icon-home"></i>
                    <a href="{{ route('admin.stock.index') }}" class="btn btn-warning btn-block btn-home-admin">Control de Stock</a>
                </div>
            </div>                   
        </div>
        
    </div>
    <hr>

@stop

resources/views/admin/template.blade.php
<!DOCTYPE html>

<html lang="es">
<head>
	<meta charset="UTF-8">
<meta charset="ISO-8859-1">
	<title>@yield('title','EM Shoes')</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha256-QSktus/KATft+5BD6tKvAwzSxP75hHX0SrIjYto471M= sha512-787L1W8XyGQkqtvQigyUGnPxsRudYU2fEunzUP5c59Z3m4pKl1YaBGTcdhfxOfBvqTmJFmb6GDgm0iQRVWOvLQ==" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
	<link href='https://fonts.googleapis.com/css?family=Poiret+One|Lobster+Two' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{{ asset('admin/css/main.css') }}">
			<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82817005-1', 'auto');
  ga('send', 'pageview');

</script>
	</head>
<body>
 
    @if(\Session::has('message'))
		@include('admin.partials.message')
    @endif
	@include('admin.partials.nav')

	@yield('content')

	@include('admin.partials.footer')
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>	
<script src="{{ asset('admin/js/main.js') }}"></script>
</body>
</html>