app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::bind('product', function($slug){
	return App\Product::where('slug', $slug)->first();
});
// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});
// Subproduct dependency injection
Route::bind('subproduct', function($subproduct){
    return App\Subproduct::find($subproduct);
});
// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});
Route::bind('user2', function($user){
    return App\User::find($user);
});
Route::bind('user3', function($user){
    return App\User::find($user);
});

Route::get('/', [
	'as' => 'home',
	'uses' => 'StoreController@index'
]);
Route::get('product/{slug}', [
	'as' => 'product-detail',
	'uses' => 'StoreController@show'
]);
// Carrito -------------
Route::get('cart/show', [
	'as' => 'cart-show',
	'uses' => 'CartController@show'
]);

Route::post('cart/add/{product}', [
	'as' => 'cart-add',
	'uses' => 'CartController@add'
]);


Route::get('cart/delete/{product}',[
	'as' => 'cart-delete',
	'uses' => 'CartController@delete'
]);
Route::get('cart/trash', [
	'as' => 'cart-trash',
	'uses' => 'CartController@trash'
]);
Route::get('cart/update/{product}/{quantity}', [
	'as' => 'cart-update',
	'uses' => 'CartController@update'
]);
Route::get('order-detail', [
	'middleware' => 'auth:user',
	'as' => 'order-detail',
	'uses' => 'CartController@orderDetail'
]);
// Authentication routes...
Route::get('auth/login', [
	'as' => 'login-get',
	'uses' => 'Auth\AuthController@getLogin'
]);
Route::post('auth/login', [
	'as' => 'login-post',
	'uses' => 'Auth\AuthController@postLogin'
]);
Route::get('auth/logout', [
	'as' => 'logout',
	'uses' => 'Auth\AuthController@getLogout'
]);
// Registration routes...
Route::get('auth/register', [
	'as' => 'register-get',
	'uses' => 'Auth\AuthController@getRegister'
]);
Route::post('auth/register', [
	'as' => 'register-post',
	'uses' => 'Auth\AuthController@postRegister'
]);

//recover

Route::get('auth/recover', [
	'as' => 'recover-get',
	'uses' => 'Auth\RecoverController@index'
]);

Route::post('auth/recover', [
	'as' => 'recover-post',
	'uses' => 'Auth\RecoverController@recover'
]);

Route::get('auth/modify/{token}', [
	'as' => 'modify-get',
	'uses' => 'Auth\ModifyController@index'
]);

Route::post('auth/modify', [
	'as' => 'modify-post',
	'uses' => 'Auth\ModifyController@modify'
]);

//Flow
Route::post('flow/confirmacion', [

	'as' => 'flow-confirmacion',
	'uses' => 'FlowController@confirmacion'
]);

Route::post('flow/fracaso', [

	'as' => 'flow-fracaso',
	'uses' => 'FlowController@fracaso'
]);

Route::post('flow/exito', [
	
	'as' => 'flow-exito',
	'uses' => 'FlowController@exito'
]);

//Khipu
Route::post('khipu/confirmacion', [

	'as' => 'khipu-confirmacion',
	'uses' => 'KhipuController@confirmacion'
]);

Route::get('khipu/fracaso', [

	'as' => 'khipu-fracaso',
	'uses' => 'KhipuController@fracaso'
]);

Route::get('khipu/exito', [

	'as' => 'khipu-exito',
	'uses' => 'KhipuController@exito'
]);

// ADMIN -------------
Route::group(['namespace' => 'Admin', 'middleware' => ['auth'], 'prefix' => 'admin'], function()
{

	Route::get('home', function(){
		return view('admin.home');
	});

	Route::resource('category', 'CategoryController');
	Route::resource('product', 'ProductController');
	Route::resource('subproduct', 'SubproductController');
	Route::resource('user', 'UserController');
	Route::resource('stock', 'StockController');
	Route::resource('reporteventas', 'ReporteVentasController');
	
	
	Route::get('orders', [
		'as' => 'admin.order.index',
		'uses' => 'OrderController@index'
	]);
	Route::post('order/get-items', [
	    'as' => 'admin.order.getItems',
	    'uses' => 'OrderController@getItems'
	]);

	
	Route::get('order/{id}', [
	    'as' => 'admin.order.destroy',
	    'uses' => 'OrderController@destroy'
	]);
	
	
		Route::post('stock', [
	    'as' => 'admin.stock.index',
	    'uses' => 'StockController@index'
	]);
	
	
	
//	Route::get('/getexport','StockController@getexport');
	
	Route::get('getexport/{cbcstock}', [
	    'as' => 'admin.stock.getexport',
	    'uses' => 'StockController@getexport'
	]);	
	
	
	
		Route::post('getexportventa/{desde}', [
	    'as' => 'admin.reporteventas.getexport',
	    'uses' => 'ReporteVentasController@getexport'
	]);	
	
	
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::resource('user2', 'UserController@edit2');

});
	
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::resource('user3', 'UserController@update');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{

		Route::get('mispedidos', [
	    'as' => 'admin.user4.mispedidos',
	    'uses' => 'UserController@mispedidos'
	]);	

});

app/Http/Controllers/Admin/StockController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;
use App\Subproduct;
use DB;
use Excel;



Use \Input as Input;

class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
	//	$elementos = Subproduct::orderBy('id','desc')->where('product_id','=',$request->get('producto'))->paginate(5);
	
	 $control = $request->get('cbcstock');
	 
	   if($control=='0' or $control==null)
	   {
		$elementos = DB::table('products')
						->select('products.id as id','products.name as productname','products.price as price'
								,'subproducts.name as subproductname','subproducts.stock as stock')
						->leftjoin('subproducts','products.id','=','subproducts.product_id')->paginate(6);
		}
		else
		{
		$elementos = DB::table('products')
						->select('products.id as id','products.name as productname','products.price as price'
								,'subproducts.name as subproductname','subproducts.stock as stock')
						->join('subproducts','products.id','=','subproducts.product_id')->paginate(6);		
		
		}
		
		
		
		
		
		
		
		return view('admin.stock.index',compact('elementos','control'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

		
    }

	
	    public function getexport(Request $request)
    {

	 $control = $request->get('cbcstock');
	 
	
			
	Excel::create('Stock-'.date("d-m-Y h:i:s A"), function($excel) use($control){

    $excel->sheet('Excel sheet', function($sheet)  use($control) {
	
	
	/// creamos los arreglos
	
	
	
	
	 	   if($control=='0' or $control==null)
	   {
		$elementos = DB::table('products')
						->select('products.id as id','products.name as productname','products.price as price'
								,'subproducts.name as subproductname','subproducts.stock as stock')
						->leftjoin('subproducts','products.id','=','subproducts.product_id')->paginate(10000);
		}
		else
		{
		$elementos = DB::table('products')
						->select('products.id as id','products.name as productname','products.price as price'
								,'subproducts.name as subproductname','subproducts.stock as stock')
						->join('subproducts','products.id','=','subproducts.product_id')->paginate(10000);		
		
		}
	
	// fin creacion arreglos
	
	$sheet->setStyle(array(
    'font' => array(
        'name'      =>  'Calibri',
        'size'      =>  14,
    )
));
	             $sheet->rows(array(
			 array('ID','NOMBRE PRODUCTO','PRECIO','NOMBRE SUBPRODUCTO','STOCK')
               )
			   );
	
		foreach($elementos as $elemento)
		{	 
			if($elemento->subproductname==null)$subname='-';else $subname=$elemento->subproductname;
	          if($elemento->stock==null)$stock='0';else $stock=$elemento->stock;
                 $sheet->rows(array(		
			                  array($elemento->id,$elemento->productname,$elemento->price,$subname,$stock)
									)
							 );
		}	

    });

	
	
})->export('xlsx');
	
    }
	
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/stock/index.blade.php
<?php

if($control==0 or $control==null)
{
$seleccion1='selected';
$seleccion2='';
}
else
{
$seleccion2='selected';
$seleccion1='';
}
?>


	@extends('admin.template')

	@section('content')
	<div class="container text-center">
	
	<div class="page-header">
		<ul class="nav nav-pills">
		 <li role="presentation" class="active"><a href="{{ route('admin.stock.index') }}">Stock</a></li>
		 <li role="presentation"><a href="{{ route('admin.reporteventas.index') }}">Ventas</a></li>
		</ul>		
	</div>
	
			<div class="page" style="background-color: #D8D8D8;">
			{!! Form::open(array('method'=>'post','route'=>'admin.stock.index')) !!}
			<div class="form-group">     
			<label for="sel11">Seleccione Todos o solo con Stock:</label>
	          <select id="cbcstock" name="cbcstock" class="form-control" >
			  <option value="0" <?php echo $seleccion1; ?>>Todos</option>
			  <option value="1" <?php echo $seleccion2; ?>>Con Stock</option>
			   </select>
			 </div> 	
					 {!! Form::submit('Consultar', array('class' => 'btn btn-primary')) !!}
					 {!! Form::close() !!}
					 
					<br>
					<h2>
					
					 <a class="btn btn-primary" href="{{ route('admin.stock.getexport') }}?cbcstock=<?=$control?>"> 
					 <i  class="fa fa-file-excel-o" style="font-size: 22px;"></i>
					 Exportar</a>
					</h2>
				<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover">
				    <thead>
                        <tr>
                            <th style="text-align: center;">id</th>
                            <th style="text-align: center;">nombre producto</th>
                            <th style="text-align: center;">Precio</th>
                            <th style="text-align: center;">Nombre Subproducto</th>
                            <th style="text-align: center;">Stock</th>
                        </tr>
                    </thead>
				<tbody>
				@foreach($elementos as $item)
				<tr>
				<td>{{$item->id}}</td>
				 <td>{{$item->productname}}</td>
				 <td>{{$item->price}}</td>
				<td><?php if($item->subproductname=='') echo '-'; else { echo $item->subproductname;  } ?></td>
				 <td><?php if($item->stock=='') echo '0'; else { echo $item->stock;  } ?></td>
				 </tr>
				@endforeach
				</tbody>
				</table>
				</div>
				 <?php echo $elementos->render(); ?>
				</div>

	</div>
	@stop